modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/Hellish-Mods/hellishtemplate/issues"

[[mods]]
modId="hellishtemplate"
version="${file.jarVersion}"

displayName="hellishtemplate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hellishtemplate"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding)
"""

description="hellishtemplate"

[[dependencies.hellishtemplate]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hellishtemplate]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"