modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/Hellish-Mods/hellish-blahaj/issues"

[[mods]]
modId="blahaj"
version="${file.jarVersion}"

displayName="Hellish Blåhaj"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hellish-blahaj"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding, Russian translation)
"""

description="Soft toy, shark mod, 16px, Hellish style."

[[dependencies.blahaj]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blahaj]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
